// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legacy_call_logs.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLegacyCallLog = `-- name: CreateLegacyCallLog :one
INSERT INTO legacy_call_logs (
    transaction_id,
    endpoint,
    method,
    status_code,
    success,
    latency_ms,
    error_message
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, transaction_id, endpoint, method, status_code, success, latency_ms, error_message, created_at
`

type CreateLegacyCallLogParams struct {
	TransactionID uuid.NullUUID  `json:"transaction_id"`
	Endpoint      string         `json:"endpoint"`
	Method        string         `json:"method"`
	StatusCode    sql.NullInt32  `json:"status_code"`
	Success       bool           `json:"success"`
	LatencyMs     int32          `json:"latency_ms"`
	ErrorMessage  sql.NullString `json:"error_message"`
}

func (q *Queries) CreateLegacyCallLog(ctx context.Context, arg CreateLegacyCallLogParams) (LegacyCallLog, error) {
	row := q.db.QueryRowContext(ctx, createLegacyCallLog,
		arg.TransactionID,
		arg.Endpoint,
		arg.Method,
		arg.StatusCode,
		arg.Success,
		arg.LatencyMs,
		arg.ErrorMessage,
	)
	var i LegacyCallLog
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.Endpoint,
		&i.Method,
		&i.StatusCode,
		&i.Success,
		&i.LatencyMs,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getLegacyCallMetrics = `-- name: GetLegacyCallMetrics :many
SELECT
    endpoint,
    success,
    COUNT(*)::bigint AS calls_total,
    COALESCE(AVG(latency_ms), 0)::bigint AS avg_latency_ms
FROM legacy_call_logs
GROUP BY endpoint, success
ORDER BY endpoint, success
`

type GetLegacyCallMetricsRow struct {
	Endpoint     string `json:"endpoint"`
	Success      bool   `json:"success"`
	CallsTotal   int64  `json:"calls_total"`
	AvgLatencyMs int64  `json:"avg_latency_ms"`
}

func (q *Queries) GetLegacyCallMetrics(ctx context.Context) ([]GetLegacyCallMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLegacyCallMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLegacyCallMetricsRow{}
	for rows.Next() {
		var i GetLegacyCallMetricsRow
		if err := rows.Scan(
			&i.Endpoint,
			&i.Success,
			&i.CallsTotal,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegacyCallLogsByTransactionID = `-- name: ListLegacyCallLogsByTransactionID :many
SELECT id, transaction_id, endpoint, method, status_code, success, latency_ms, error_message, created_at
FROM legacy_call_logs
WHERE transaction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListLegacyCallLogsByTransactionID(ctx context.Context, transactionID uuid.NullUUID) ([]LegacyCallLog, error) {
	rows, err := q.db.QueryContext(ctx, listLegacyCallLogsByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LegacyCallLog{}
	for rows.Next() {
		var i LegacyCallLog
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Endpoint,
			&i.Method,
			&i.StatusCode,
			&i.Success,
			&i.LatencyMs,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
