// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchants.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (
    name,
    qris_code,
    category
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, qris_code, category, created_at
`

type CreateMerchantParams struct {
	Name     string         `json:"name"`
	QrisCode string         `json:"qris_code"`
	Category sql.NullString `json:"category"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, createMerchant, arg.Name, arg.QrisCode, arg.Category)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.QrisCode,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, name, qris_code, category, created_at
FROM merchants
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.QrisCode,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantByQRISCode = `-- name: GetMerchantByQRISCode :one
SELECT id, name, qris_code, category, created_at
FROM merchants
WHERE qris_code = $1
LIMIT 1
`

func (q *Queries) GetMerchantByQRISCode(ctx context.Context, qrisCode string) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByQRISCode, qrisCode)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.QrisCode,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}
