// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	AccountNumber string    `json:"account_number"`
	Balance       int64     `json:"balance"`
	CreatedAt     time.Time `json:"created_at"`
}

type BenchmarkResult struct {
	ID                 uuid.UUID      `json:"id"`
	BenchmarkRunID     uuid.UUID      `json:"benchmark_run_id"`
	TotalRequests      int32          `json:"total_requests"`
	SuccessfulRequests int32          `json:"successful_requests"`
	FailedRequests     int32          `json:"failed_requests"`
	P50LatencyMs       sql.NullInt32  `json:"p50_latency_ms"`
	P95LatencyMs       sql.NullInt32  `json:"p95_latency_ms"`
	P99LatencyMs       sql.NullInt32  `json:"p99_latency_ms"`
	ThroughputRps      sql.NullString `json:"throughput_rps"`
	ErrorRate          sql.NullString `json:"error_rate"`
	CacheHitRate       sql.NullString `json:"cache_hit_rate"`
	CreatedAt          time.Time      `json:"created_at"`
}

type BenchmarkRun struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	Mode           string         `json:"mode"`
	VirtualUsers   sql.NullInt32  `json:"virtual_users"`
	NetworkProfile sql.NullString `json:"network_profile"`
	StartedAt      time.Time      `json:"started_at"`
	FinishedAt     sql.NullTime   `json:"finished_at"`
}

type CacheMetric struct {
	ID        uuid.UUID `json:"id"`
	CacheKey  string    `json:"cache_key"`
	Operation string    `json:"operation"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

type LegacyCallLog struct {
	ID            uuid.UUID      `json:"id"`
	TransactionID uuid.NullUUID  `json:"transaction_id"`
	Endpoint      string         `json:"endpoint"`
	Method        string         `json:"method"`
	StatusCode    sql.NullInt32  `json:"status_code"`
	Success       bool           `json:"success"`
	LatencyMs     int32          `json:"latency_ms"`
	ErrorMessage  sql.NullString `json:"error_message"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Merchant struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	QrisCode  string         `json:"qris_code"`
	Category  sql.NullString `json:"category"`
	CreatedAt time.Time      `json:"created_at"`
}

type Transaction struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	MerchantID        uuid.UUID      `json:"merchant_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	Amount            int64          `json:"amount"`
	Status            string         `json:"status"`
	IdempotencyKey    string         `json:"idempotency_key"`
	LegacyReferenceID sql.NullString `json:"legacy_reference_id"`
	FailureReason     sql.NullString `json:"failure_reason"`
	RequestedAt       time.Time      `json:"requested_at"`
	ProcessedAt       sql.NullTime   `json:"processed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type TransactionEvent struct {
	ID            uuid.UUID       `json:"id"`
	TransactionID uuid.UUID       `json:"transaction_id"`
	EventType     string          `json:"event_type"`
	Message       sql.NullString  `json:"message"`
	Metadata      json.RawMessage `json:"metadata"`
	CreatedAt     time.Time       `json:"created_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	CreatedAt   time.Time      `json:"created_at"`
}
