// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    merchant_id,
    account_id,
    amount,
    status,
    idempotency_key,
    legacy_reference_id,
    failure_reason,
    processed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, user_id, merchant_id, account_id, amount, status, idempotency_key, legacy_reference_id, failure_reason, requested_at, processed_at, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID            uuid.UUID      `json:"user_id"`
	MerchantID        uuid.NullUUID  `json:"merchant_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	Amount            int64          `json:"amount"`
	Status            string         `json:"status"`
	IdempotencyKey    string         `json:"idempotency_key"`
	LegacyReferenceID sql.NullString `json:"legacy_reference_id"`
	FailureReason     sql.NullString `json:"failure_reason"`
	ProcessedAt       sql.NullTime   `json:"processed_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.MerchantID,
		arg.AccountID,
		arg.Amount,
		arg.Status,
		arg.IdempotencyKey,
		arg.LegacyReferenceID,
		arg.FailureReason,
		arg.ProcessedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.LegacyReferenceID,
		&i.FailureReason,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionEvent = `-- name: CreateTransactionEvent :one
INSERT INTO transaction_events (
    transaction_id,
    event_type,
    message,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, transaction_id, event_type, message, metadata, created_at
`

type CreateTransactionEventParams struct {
	TransactionID uuid.UUID       `json:"transaction_id"`
	EventType     string          `json:"event_type"`
	Message       sql.NullString  `json:"message"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateTransactionEvent(ctx context.Context, arg CreateTransactionEventParams) (TransactionEvent, error) {
	row := q.db.QueryRowContext(ctx, createTransactionEvent,
		arg.TransactionID,
		arg.EventType,
		arg.Message,
		arg.Metadata,
	)
	var i TransactionEvent
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.EventType,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, merchant_id, account_id, amount, status, idempotency_key, legacy_reference_id, failure_reason, requested_at, processed_at, created_at, updated_at
FROM transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.LegacyReferenceID,
		&i.FailureReason,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, user_id, merchant_id, account_id, amount, status, idempotency_key, legacy_reference_id, failure_reason, requested_at, processed_at, created_at, updated_at
FROM transactions
WHERE idempotency_key = $1
LIMIT 1
`

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, idempotencyKey string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByIdempotencyKey, idempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.LegacyReferenceID,
		&i.FailureReason,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionStateCounts = `-- name: GetTransactionStateCounts :many
SELECT
    status,
    COUNT(*)::bigint AS transactions_total
FROM transactions
GROUP BY status
ORDER BY status
`

type GetTransactionStateCountsRow struct {
	Status            string `json:"status"`
	TransactionsTotal int64  `json:"transactions_total"`
}

func (q *Queries) GetTransactionStateCounts(ctx context.Context) ([]GetTransactionStateCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionStateCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionStateCountsRow{}
	for rows.Next() {
		var i GetTransactionStateCountsRow
		if err := rows.Scan(&i.Status, &i.TransactionsTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionStatusByID = `-- name: GetTransactionStatusByID :one
SELECT id, status, requested_at, processed_at, updated_at
FROM transactions
WHERE id = $1
LIMIT 1
`

type GetTransactionStatusByIDRow struct {
	ID          uuid.UUID    `json:"id"`
	Status      string       `json:"status"`
	RequestedAt time.Time    `json:"requested_at"`
	ProcessedAt sql.NullTime `json:"processed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

func (q *Queries) GetTransactionStatusByID(ctx context.Context, id uuid.UUID) (GetTransactionStatusByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionStatusByID, id)
	var i GetTransactionStatusByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionEventsByTransactionID = `-- name: ListTransactionEventsByTransactionID :many
SELECT id, transaction_id, event_type, message, metadata, created_at
FROM transaction_events
WHERE transaction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTransactionEventsByTransactionID(ctx context.Context, transactionID uuid.UUID) ([]TransactionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionEventsByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransactionEvent{}
	for rows.Next() {
		var i TransactionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.EventType,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountID = `-- name: ListTransactionsByAccountID :many
SELECT id, user_id, merchant_id, account_id, amount, status, idempotency_key, legacy_reference_id, failure_reason, requested_at, processed_at, created_at, updated_at
FROM transactions
WHERE account_id = $1
  AND (
    $2 = TIMESTAMPTZ '0001-01-01 00:00:00+00'
    OR created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTransactionsByAccountIDParams struct {
	AccountID uuid.UUID   `json:"account_id"`
	Column2   interface{} `json:"column_2"`
	ID        uuid.UUID   `json:"id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListTransactionsByAccountID(ctx context.Context, arg ListTransactionsByAccountIDParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByAccountID,
		arg.AccountID,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.AccountID,
			&i.Amount,
			&i.Status,
			&i.IdempotencyKey,
			&i.LegacyReferenceID,
			&i.FailureReason,
			&i.RequestedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2,
    failure_reason = $3,
    processed_at = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, merchant_id, account_id, amount, status, idempotency_key, legacy_reference_id, failure_reason, requested_at, processed_at, created_at, updated_at
`

type UpdateTransactionStatusParams struct {
	ID            uuid.UUID      `json:"id"`
	Status        string         `json:"status"`
	FailureReason sql.NullString `json:"failure_reason"`
	ProcessedAt   sql.NullTime   `json:"processed_at"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.ProcessedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.AccountID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.LegacyReferenceID,
		&i.FailureReason,
		&i.RequestedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
