name: CI

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          
      - name: Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/security-audit"

      - name: Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          
      - name: Test script
        run: echo Dante is running!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
