name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Dependency vulnerability scan
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

      # Secret scanning
      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2

      # Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: golang

      # Autobuild project
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # Run CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # Example build/test
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
